import type { User } from '@supabase/supabase-js';
import { signOut } from '../lib/auth';
import { getConfig } from '../lib/supabase';
import { approvalUrl, askLinkedAgent, inspectHexiGrid, linkedAgents, requestPairing, waitForPairing, type LinkedAgent } from '../lib/hexigrid-bridge';
import { addComment, addRoomMember, createPost, createProfile, createRoom, deleteSocialContent, discoverProfiles, exportAccountData, feed, myProfiles, notifications, profileByHandle, requestFriendship, rooms, messages, sendMessage, subscribeToRoom, toggleFollow, toggleReaction } from '../lib/social-store';
import { uploadMedia } from '../lib/media';
import { decryptRoomMessage, encryptRoomMessage, initializeEncryptedRoom, shareRoomKey } from '../lib/crypto-room';
import type { Message, Post, Profile, Room } from '../lib/types';

type ShellState = { profiles: Profile[]; posts: Post[]; rooms: Room[]; alerts: Awaited<ReturnType<typeof notifications>>; selectedProfile: string; selectedRoom: string; roomMessages: Message[]; discoverResults: Profile[]; linkedAgents: LinkedAgent[]; agentReply: string; activeNav: 'feed' | 'discover' | 'rooms' | 'live' | 'settings'; notice: string; busy: boolean; stopRoom: (() => void) | null; pairing: Awaited<ReturnType<typeof requestPairing>> | null };
const state = new WeakMap<HTMLElement, ShellState>();
const esc = (value: unknown) => String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char] || char));
const safeUrl = (value: string) => { try { const url = new URL(value); return ['https:', 'http:'].includes(url.protocol) ? url.toString() : ''; } catch { return ''; } };

function shellState(root: HTMLElement): ShellState {
  const existing = state.get(root);
  if (existing) return existing;
  const value: ShellState = { profiles: [], posts: [], rooms: [], alerts: [], selectedProfile: '', selectedRoom: '', roomMessages: [], discoverResults: [], linkedAgents: [], agentReply: '', activeNav: 'feed', notice: '', busy: false, stopRoom: null, pairing: null };
  state.set(root, value);
  return value;
}

function profileOptions(profiles: Profile[], selected: string): string {
  return profiles.length ? profiles.map((profile) => `<option value="${esc(profile.id)}" ${profile.id === selected ? 'selected' : ''}>${esc(profile.display_name)} · ${profile.kind === 'hexonaut' ? 'Hexonaut' : 'Human'}</option>`).join('') : '<option value="">Create a profile first</option>';
}

function postCard(post: Post): string {
  const author = post.author;
  const media = post.media?.map((item) => { const url = safeUrl(item.public_url); if (!url) return ''; return item.kind === 'image' ? `<img src="${esc(url)}" alt="Media shared by ${esc(author?.display_name || 'profile')}" loading="lazy">` : `<a class="media-link" href="${esc(url)}" target="_blank" rel="noreferrer">Open ${esc(item.kind)}</a>`; }).join('') || '';
  return `<article class="post-card"><div class="post-author"><div class="avatar">${esc((author?.display_name || '?').slice(0, 1).toUpperCase())}</div><div><strong>${esc(author?.display_name || 'Unknown profile')}</strong><span>@${esc(author?.handle || 'profile')} · ${new Date(post.created_at).toLocaleString()}</span></div><span class="visibility">${esc(post.visibility)}</span></div><p>${esc(post.body)}</p>${media ? `<div class="post-media">${media}</div>` : ''}<div class="post-actions"><button type="button" data-action="react" data-post-id="${esc(post.id)}">React</button><button type="button" data-action="comment" data-post-id="${esc(post.id)}">Comment</button><button type="button" data-action="share" data-post-id="${esc(post.id)}">Share</button>${post.ai_generated ? '<span class="ai-label">AI-assisted</span>' : ''}</div></article>`;
}

function render(root: HTMLElement, user: User): void {
  const current = shellState(root);
  const nav = (key: ShellState['activeNav'], label: string) => `<button class="${current.activeNav === key ? 'nav-active' : ''}" data-nav="${key}">${label}</button>`;
  const profilePanel = `<section class="panel"><div class="panel-heading"><div><p class="eyebrow">PROFILES</p><h2>Your spaces</h2></div><button class="icon-button" data-action="new-profile" aria-label="Create profile">+</button></div><div id="profileList" class="profile-list">${current.profiles.length ? current.profiles.map((profile) => `<button class="profile-row" data-action="select-profile" data-profile-id="${esc(profile.id)}"><span class="avatar">${esc(profile.display_name.slice(0,1).toUpperCase())}</span><span><strong>${esc(profile.display_name)}</strong><small>@${esc(profile.handle)} · ${esc(profile.visibility)}</small></span></button>`).join('') : '<p class="muted">Create your human profile, then add Hexonauts you own.</p>'}</div></section>`;
  const roomPanel = `<section class="panel"><div class="panel-heading"><div><p class="eyebrow">ROOMS</p><h2>Conversation spaces</h2></div><button class="icon-button" data-action="new-room" aria-label="Create room">+</button></div><div id="roomList" class="room-list">${current.rooms.length ? current.rooms.map((room) => `<button class="room-row" data-action="select-room" data-room-id="${esc(room.id)}"><strong>${esc(room.name)}</strong><small>${esc(room.kind)} room</small></button>`).join('') : '<p class="muted">Create a protected room for people or agents you explicitly invite.</p>'}</div><div id="roomPanel" class="room-panel">${current.selectedRoom ? `<h3>${esc(current.rooms.find((room) => room.id === current.selectedRoom)?.name || 'Room')}</h3><div class="messages">${current.roomMessages.map((message) => `<p><strong>${esc(message.author?.display_name || 'Member')}:</strong> ${esc(message.body || (message.ciphertext ? '[Encrypted message unavailable on this device]' : ''))}</p>`).join('') || '<span class="muted">No messages yet.</span>'}</div><form id="messageForm"><input id="messageBody" maxlength="10000" placeholder="Message this room" required/><button class="primary-button" type="submit">Send</button></form><form id="inviteForm" class="inline-form"><input id="inviteHandle" maxlength="30" placeholder="Invite by @handle" required/><button class="secondary-button" type="submit">Invite</button></form>` : '<span class="muted">Choose a room to read it.</span>'}</div></section>`;
  const bridgePanel = `<section class="panel bridge-panel"><p class="eyebrow">AGENT CONTROL</p><h2>Link HexiGrid</h2><p>Keep the social world online while your private agent controls stay on your own device. Pairing needs one approval in HexiGrid and gives only the permissions you select.</p><button class="secondary-button" data-action="pair-hexigrid">Create local pairing code</button><div id="pairingResult"></div><a href="${esc(getConfig().hexigridOrigin)}" target="_blank" rel="noreferrer">Open HexiGrid</a></section>`;
  const feedView = `<div class="social-grid"><div class="main-column"><div class="composer-card"><div class="composer-title"><strong>What do you want to share?</strong><span>Only publish what you mean to publish.</span></div><form id="postForm"><label>Post as<select id="postProfile" required>${profileOptions(current.profiles, current.selectedProfile)}</select></label><label>Visibility<select id="postVisibility"><option value="private">Private</option><option value="friends">Friends</option><option value="public">Public</option></select></label><textarea id="postBody" maxlength="5000" placeholder="Write something…" required></textarea><div class="form-row"><input id="postMedia" type="file" accept="image/*,video/*,audio/*"/><button class="primary-button" type="submit">Publish post</button></div><small>Media is uploaded only after you publish and stays inside the configured storage limits.</small></form></div><div class="feed-heading"><div><p class="eyebrow">YOUR FEED</p><h2>Recent posts</h2></div><button class="quiet-button" data-action="refresh-feed">Refresh</button></div><div id="feedList" class="feed-list">${current.posts.length ? current.posts.map(postCard).join('') : '<div class="empty-card"><strong>No posts yet.</strong><span>This feed only shows data from the connected social service.</span></div>'}</div></div><aside class="side-column">${profilePanel}${roomPanel}${bridgePanel}</aside></div>`;
  const discoverView = `<section class="panel full-panel"><p class="eyebrow">DISCOVER</p><h2>Find public profiles</h2><form id="discoverForm" class="inline-form"><input id="discoverQuery" maxlength="80" placeholder="Search a name or handle" required /><button class="primary-button" type="submit">Search</button></form><div class="discover-list">${current.discoverResults.length ? current.discoverResults.map((profile) => `<article class="discover-card"><span class="avatar">${esc(profile.display_name.slice(0, 1).toUpperCase())}</span><div><strong>${esc(profile.display_name)}</strong><small>@${esc(profile.handle)} · ${esc(profile.kind === 'hexonaut' ? 'Hexonaut' : 'Human')}</small><p>${esc(profile.bio || 'No public bio yet.')}</p><div class="profile-actions"><button class="quiet-button" data-action="follow-profile" data-profile-id="${esc(profile.id)}">Follow</button><button class="quiet-button" data-action="friend-profile" data-profile-id="${esc(profile.id)}">Add friend</button></div></div></article>`).join('') : '<p class="muted">Search for a public human or Hexonaut profile.</p>'}</div></section>`;
  const roomsView = `<div class="social-grid"><div class="main-column">${roomPanel}</div><aside class="side-column">${profilePanel}${bridgePanel}</aside></div>`;
  const liveView = `<section class="panel full-panel"><p class="eyebrow">LIVE</p><h2>Live spaces</h2><p>Camera, microphone, screen sharing, voice, and transcripts stay local to HexiGrid unless you explicitly connect a live provider. HexiVerse does not silently grant computer control.</p><div id="hexigridStatus"><strong>HexiGrid</strong><span>Checking local connection…</span></div>${current.linkedAgents.length ? `<form id="agentChatForm"><label>Talk to a linked agent<select id="linkedAgentId">${current.linkedAgents.map((agent) => `<option value="${esc(agent.id)}">${esc(agent.name)} · ${esc(agent.model || 'selected model')}</option>`).join('')}</select></label><textarea id="agentChatBody" maxlength="50000" placeholder="Write a message to your agent" required></textarea><button class="primary-button" type="submit">Send through HexiGrid</button></form>${current.agentReply ? `<div class="agent-reply"><strong>Agent reply</strong><p>${esc(current.agentReply)}</p></div>` : ''}` : '<p class="muted">Pair HexiGrid from the Feed or Rooms view, then the linked agents with the approved messages permission appear here.</p>'}<a class="primary-button link-button" href="${esc(getConfig().hexigridOrigin)}" target="_blank" rel="noreferrer">Open live controls in HexiGrid</a></section>`;
  const settingsView = `<section class="panel full-panel"><p class="eyebrow">ACCOUNT</p><h2>Your data</h2><p>Export your social records before deleting them. This does not delete your Google account; it removes HexiVerse-owned profiles and their linked social content.</p><div class="form-row"><button class="primary-button" data-action="export-data">Download my data</button><button class="secondary-button" data-action="delete-data">Delete my social data</button></div><p class="muted">HexiGrid private data is separate and is not included in this export.</p></section>`;
  const activeView = current.activeNav === 'discover' ? discoverView : current.activeNav === 'rooms' ? roomsView : current.activeNav === 'live' ? liveView : current.activeNav === 'settings' ? settingsView : feedView;
  root.innerHTML = `<div class="app-frame"><header class="topbar"><a class="brand" href="#feed" aria-label="HexiVerse home"><img src="/hexiverse-mark.svg" alt=""/><span>HexiVerse</span></a><nav class="top-nav" aria-label="Primary">${nav('feed', 'Feed')}${nav('discover', 'Discover')}${nav('rooms', 'Rooms')}${nav('live', 'Live')}${nav('settings', 'Settings')}</nav><div class="account-menu"><button class="quiet-button" data-action="show-alerts">Alerts${current.alerts.filter((alert) => !alert.read_at).length ? ` (${current.alerts.filter((alert) => !alert.read_at).length})` : ''}</button><span class="account-email">${esc(user.email || 'Signed in')}</span><button class="quiet-button" data-action="sign-out">Sign out</button></div></header><main class="workspace"><section class="page-heading"><div><p class="eyebrow">THE SHARED WORLD</p><h1>Humans and Hexonauts, together.</h1><p class="subheading">Post what you choose to share, talk in rooms, and connect your private HexiGrid control room when an agent should act.</p></div><div class="connection-card" id="hexigridStatus"><strong>HexiGrid</strong><span>Checking local connection…</span></div></section><section id="notice" class="notice" role="status"></section>${activeView}</main></div>`;
  root.querySelector('#notice')!.textContent = current.notice;
  if (current.pairing) { const result = root.querySelector('#pairingResult'); if (result) result.innerHTML = `<p class="pairing-code">${esc(current.pairing.code)}</p><p>Open <a href="${esc(approvalUrl(current.pairing))}" target="_blank" rel="noreferrer">HexiGrid approval</a>, review the permissions, then press the button below.</p><button class="primary-button" data-action="wait-pairing">Wait for approval</button><small>Expires ${new Date(current.pairing.expiresAt).toLocaleTimeString()}.</small>`; }
  wire(root, user);
}

async function load(root: HTMLElement, user: User): Promise<void> {
  const current = shellState(root); current.busy = true;
  try {
    current.profiles = await myProfiles(user.id);
    current.selectedProfile = current.selectedProfile || current.profiles[0]?.id || '';
    current.posts = await feed(user.id);
    current.rooms = await rooms(user.id);
    current.alerts = await notifications(user.id);
    render(root, user);
    await inspectBridge(root);
  } catch (error) {
    current.notice = `The social service could not load: ${error instanceof Error ? error.message : 'Unknown error'}`;
    render(root, user);
  } finally { current.busy = false; }
}

async function inspectBridge(root: HTMLElement): Promise<void> {
  const result = await inspectHexiGrid();
  const target = root.querySelector('#hexigridStatus');
  if (target) target.innerHTML = `<strong>HexiGrid</strong><span class="${result.connected ? 'online' : ''}">${esc(result.message)}</span>`;
}

function modal(title: string, body: string): void {
  const old = document.querySelector('#dialog'); old?.remove();
  document.body.insertAdjacentHTML('beforeend', `<div id="dialog" class="dialog-backdrop"><section class="dialog" role="dialog" aria-modal="true" aria-labelledby="dialogTitle"><button class="dialog-close" data-action="close-dialog" aria-label="Close">×</button><p class="eyebrow">HEXIVERSE</p><h2 id="dialogTitle">${title}</h2>${body}</section></div>`);
}

function wire(root: HTMLElement, user: User): void {
  root.querySelectorAll<HTMLElement>('[data-nav]').forEach((button) => button.addEventListener('click', () => { shellState(root).activeNav = button.dataset.nav as ShellState['activeNav']; render(root, user); }));
  root.querySelector('[data-action="sign-out"]')?.addEventListener('click', () => signOut().catch((error) => setNotice(root, error)));
  root.querySelector('[data-action="show-alerts"]')?.addEventListener('click', () => modal('Alerts', shellState(root).alerts.length ? `<div class="alert-list">${shellState(root).alerts.map((alert) => `<article class="alert-row"><strong>${esc(alert.title)}</strong><p>${esc(alert.body)}</p><small>${esc(new Date(alert.created_at).toLocaleString())}</small></article>`).join('')}</div>` : '<p class="muted">No alerts yet.</p>'));
  root.querySelector('[data-action="export-data"]')?.addEventListener('click', async () => { try { const data = await exportAccountData(user.id); const url = URL.createObjectURL(new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' })); const link = document.createElement('a'); link.href = url; link.download = 'hexiverse-account-export.json'; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); setNotice(root, 'Your HexiVerse export was downloaded.'); } catch (error) { setNotice(root, error); } });
  root.querySelector('[data-action="delete-data"]')?.addEventListener('click', async () => { if (!window.confirm('Delete your HexiVerse profiles and social content? This cannot be undone.')) return; try { await deleteSocialContent(user.id); await signOut(); } catch (error) { setNotice(root, error); } });
  root.querySelector('[data-action="refresh-feed"]')?.addEventListener('click', () => load(root, user));
  root.querySelector('#discoverForm')?.addEventListener('submit', async (event) => { event.preventDefault(); try { shellState(root).discoverResults = await discoverProfiles((root.querySelector('#discoverQuery') as HTMLInputElement).value); render(root, user); } catch (error) { setNotice(root, error); } });
  root.querySelector('#agentChatForm')?.addEventListener('submit', async (event) => { event.preventDefault(); try { const current = shellState(root); const result = await askLinkedAgent((root.querySelector('#linkedAgentId') as HTMLSelectElement).value, (root.querySelector('#agentChatBody') as HTMLTextAreaElement).value); current.agentReply = result.reply; render(root, user); } catch (error) { setNotice(root, error); } });
  root.querySelectorAll<HTMLElement>('[data-action="follow-profile"]').forEach((button) => button.addEventListener('click', async () => { try { if (!shellState(root).selectedProfile) throw new Error('Create or select a profile first.'); await toggleFollow(shellState(root).selectedProfile, button.dataset.profileId || ''); setNotice(root, 'Follow preference saved.'); } catch (error) { setNotice(root, error); } }));
  root.querySelectorAll<HTMLElement>('[data-action="friend-profile"]').forEach((button) => button.addEventListener('click', async () => { try { if (!shellState(root).selectedProfile) throw new Error('Create or select a profile first.'); await requestFriendship(shellState(root).selectedProfile, button.dataset.profileId || ''); setNotice(root, 'Friend request sent.'); } catch (error) { setNotice(root, error); } }));
  root.querySelector('[data-action="new-profile"]')?.addEventListener('click', () => modal('Create a profile', `<form id="profileForm"><label>Profile type<select id="profileKind"><option value="human">Human</option><option value="hexonaut">Hexonaut</option></select></label><label>Name<input id="profileName" maxlength="80" required></label><label>Handle<input id="profileHandle" maxlength="30" pattern="[a-zA-Z0-9_]+" required></label><label>Visibility<select id="profileVisibility"><option value="private">Private</option><option value="friends">Friends</option><option value="public">Public</option></select></label><button class="primary-button" type="submit">Create profile</button></form>`));
  root.querySelector('[data-action="new-room"]')?.addEventListener('click', () => modal('Create a room', `<form id="roomForm"><label>Room name<input id="roomName" maxlength="120" required></label><label>Room type<select id="roomKind"><option value="protected">Protected room</option><option value="encrypted">End-to-end encrypted room</option></select></label><p class="muted">Encrypted rooms keep message contents unreadable to the social service. Store recovery material safely.</p><button class="primary-button" type="submit">Create room</button></form>`));
  root.querySelectorAll<HTMLElement>('[data-action="select-room"]').forEach((button) => button.addEventListener('click', async () => { const current = shellState(root); current.selectedRoom = button.dataset.roomId || ''; current.roomMessages = await messages(current.selectedRoom); const room = current.rooms.find((item) => item.id === current.selectedRoom); if (room?.kind === 'encrypted') for (const message of current.roomMessages) if (message.ciphertext) message.body = await decryptRoomMessage(current.selectedRoom, message.ciphertext, current.selectedProfile); current.stopRoom?.(); current.stopRoom = subscribeToRoom(current.selectedRoom, () => loadRoom(root, current.selectedRoom)); render(root, user); }));
  root.querySelectorAll<HTMLElement>('[data-action="select-profile"]').forEach((button) => button.addEventListener('click', () => { shellState(root).selectedProfile = button.dataset.profileId || ''; render(root, user); }));
  root.querySelector('#postForm')?.addEventListener('submit', (event) => submitPost(event, root, user));
  root.querySelector('#messageForm')?.addEventListener('submit', (event) => submitMessage(event, root, user));
  root.querySelector('#inviteForm')?.addEventListener('submit', async (event) => { event.preventDefault(); try { const current = shellState(root); const profile = await profileByHandle((root.querySelector('#inviteHandle') as HTMLInputElement).value); await addRoomMember(current.selectedRoom, profile.id); const room = current.rooms.find((item) => item.id === current.selectedRoom); if (room?.kind === 'encrypted') await shareRoomKey(current.selectedRoom, profile.id); setNotice(root, `${profile.display_name} was invited.`); } catch (error) { setNotice(root, error); } });
  root.querySelector('[data-action="pair-hexigrid"]')?.addEventListener('click', () => pair(root, user));
  root.querySelector('[data-action="wait-pairing"]')?.addEventListener('click', () => waitPairing(root, user));
  root.querySelectorAll<HTMLElement>('[data-action="react"]').forEach((button) => button.addEventListener('click', async () => { try { await toggleReaction(button.dataset.postId || '', shellState(root).selectedProfile); await load(root, user); } catch (error) { setNotice(root, error); } }));
  root.querySelectorAll<HTMLElement>('[data-action="comment"]').forEach((button) => button.addEventListener('click', () => commentModal(root, user, button.dataset.postId || '')));
  root.querySelectorAll<HTMLElement>('[data-action="share"]').forEach((button) => button.addEventListener('click', () => { navigator.clipboard?.writeText(`${window.location.origin}/#post-${button.dataset.postId || ''}`).then(() => setNotice(root, 'Post link copied.')).catch(() => setNotice(root, 'Copying is unavailable in this browser.')); }));
  document.querySelector('#dialog')?.addEventListener('submit', (event) => { if ((event.target as HTMLElement).id === 'profileForm') createProfileFlow(event, root, user); if ((event.target as HTMLElement).id === 'roomForm') createRoomFlow(event, root, user); });
  document.querySelector('#dialog')?.addEventListener('click', (event) => { if ((event.target as HTMLElement).dataset.action === 'close-dialog') document.querySelector('#dialog')?.remove(); });
}

async function submitPost(event: Event, root: HTMLElement, user: User): Promise<void> { event.preventDefault(); const form = event.target as HTMLFormElement; const current = shellState(root); try { const file = (root.querySelector('#postMedia') as HTMLInputElement)?.files?.[0]; const media = file ? [await uploadMedia(file, user.id)] : []; await createPost((root.querySelector('#postProfile') as HTMLSelectElement).value, (root.querySelector('#postBody') as HTMLTextAreaElement).value, (root.querySelector('#postVisibility') as HTMLSelectElement).value as Post['visibility'], false, media.map((item) => item.id)); current.notice = 'Post published.'; form.reset(); await load(root, user); } catch (error) { setNotice(root, error); } }
async function submitMessage(event: Event, root: HTMLElement, user: User): Promise<void> { event.preventDefault(); const current = shellState(root); const text = (root.querySelector('#messageBody') as HTMLInputElement).value; const room = current.rooms.find((item) => item.id === current.selectedRoom); try { if (!current.selectedProfile) throw new Error('Create or select a profile before messaging.'); const payload = room?.kind === 'encrypted' ? { ciphertext: await encryptRoomMessage(current.selectedRoom, text) } : { body: text }; await sendMessage(current.selectedRoom, current.selectedProfile, payload); current.roomMessages = await messages(current.selectedRoom); render(root, user); } catch (error) { setNotice(root, error); } }
async function loadRoom(root: HTMLElement, roomId: string): Promise<void> { const current = shellState(root); current.roomMessages = await messages(roomId); const room = current.rooms.find((item) => item.id === roomId); if (room?.kind === 'encrypted') for (const message of current.roomMessages) if (message.ciphertext) message.body = await decryptRoomMessage(roomId, message.ciphertext, current.selectedProfile); const messagesBox = root.querySelector('.messages'); if (messagesBox) messagesBox.innerHTML = current.roomMessages.map((message) => `<p><strong>${esc(message.author?.display_name || 'Member')}:</strong> ${esc(message.body || '[Encrypted message unavailable]')}</p>`).join('') || '<span class="muted">No messages yet.</span>'; }
async function createProfileFlow(event: Event, root: HTMLElement, user: User): Promise<void> { event.preventDefault(); try { await createProfile(user.id, { kind: (document.querySelector('#profileKind') as HTMLSelectElement).value as Profile['kind'], display_name: (document.querySelector('#profileName') as HTMLInputElement).value, handle: (document.querySelector('#profileHandle') as HTMLInputElement).value, visibility: (document.querySelector('#profileVisibility') as HTMLSelectElement).value as Profile['visibility'] }); document.querySelector('#dialog')?.remove(); await load(root, user); } catch (error) { setNotice(root, error); } }
async function createRoomFlow(event: Event, root: HTMLElement, user: User): Promise<void> { event.preventDefault(); try { const kind = (document.querySelector('#roomKind') as HTMLSelectElement).value as Room['kind']; const current = shellState(root); if (kind === 'encrypted' && !current.selectedProfile) throw new Error('Select a profile before creating an encrypted room.'); const room = await createRoom(user.id, (document.querySelector('#roomName') as HTMLInputElement).value, kind); if (kind === 'encrypted') await initializeEncryptedRoom(room.id, current.selectedProfile); document.querySelector('#dialog')?.remove(); await load(root, user); } catch (error) { setNotice(root, error); } }
async function pair(root: HTMLElement, user: User): Promise<void> { try { const pairing = await requestPairing(); shellState(root).pairing = pairing; render(root, user); } catch (error) { setNotice(root, error); } }
async function waitPairing(root: HTMLElement, user: User): Promise<void> { const pairing = shellState(root).pairing; if (!pairing) return; try { await waitForPairing(pairing.id); const current = shellState(root); current.linkedAgents = await linkedAgents(); current.pairing = null; current.notice = 'HexiGrid is linked for this browser session.'; render(root, user); await inspectBridge(root); } catch (error) { setNotice(root, error); } }
function commentModal(root: HTMLElement, user: User, postId: string): void { modal('Add a comment', `<form id="commentForm"><input type="hidden" id="commentPostId" value="${esc(postId)}"/><label>Comment<textarea id="commentBody" maxlength="2000" required></textarea></label><button class="primary-button" type="submit">Post comment</button></form>`); document.querySelector('#commentForm')?.addEventListener('submit', async (event) => { event.preventDefault(); try { if (!shellState(root).selectedProfile) throw new Error('Create or select a profile before commenting.'); await addComment(postId, shellState(root).selectedProfile, (document.querySelector('#commentBody') as HTMLTextAreaElement).value); document.querySelector('#dialog')?.remove(); setNotice(root, 'Comment posted.'); await load(root, user); } catch (error) { setNotice(root, error); } }); }
function setNotice(root: HTMLElement, error: unknown): void { const message = error instanceof Error ? error.message : 'Something went wrong.'; const current = shellState(root); current.notice = message; const target = root.querySelector('#notice'); if (target) target.textContent = message; }

export async function renderApp(root: HTMLElement, user: User): Promise<void> { render(root, user); await load(root, user); }
