import { listSavedModelConnections, modelProviders } from '../lib/model-connections';
import { themeOptions } from '../lib/theme-system';

const esc = (value: unknown) => String(value ?? '').replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[character] || character));

export function renderModelSettings(stopped: boolean, selectedTheme = 'dark'): string {
  const providers = modelProviders.map((item) => `<option value="${item.id}" data-endpoint="${esc(item.endpoint)}">${item.name}</option>`).join('');
  const saved = listSavedModelConnections();
  const savedConnections = saved.length ? `<details class="setup-card saved-models"><summary>Use a saved model</summary><p class="muted">Your key is encrypted on this browser. Enter the phrase you created to unlock it for this session.</p><form id="modelUnlockForm"><label>Saved model<select id="modelSavedId" ${stopped ? 'disabled' : ''}>${saved.map((item) => `<option value="${esc(item.id)}">${esc(modelProviders.find((provider) => provider.id === item.provider)?.name || item.provider)} · ${esc(item.model)}</option>`).join('')}</select></label><label>Unlock phrase<input id="modelUnlockPassphrase" type="password" autocomplete="current-password" ${stopped ? 'disabled' : ''}/></label><button class="secondary-button" type="submit" ${stopped ? 'disabled' : ''}>Unlock model</button></form><p id="modelUnlockStatus" class="muted" role="status"></p></details>` : '';
  const defaultEndpoint = modelProviders[0]?.endpoint || '';
  return `<section class="panel full-panel model-settings"><p class="eyebrow">MODEL CONNECTION</p><h2>Connect a model</h2><p>Connect straight from this device. Your key is encrypted in this browser and is not saved to HexiSpace. When you use the model, its key goes directly to the provider. Anyone using this browser while it is unlocked could use that connection.</p>${stopped ? '<div class="offline-status"><strong>Agent activity is stopped.</strong><span>Resume it from the account menu before testing a model.</span></div>' : ''}<form id="modelConnectionForm"><label>Provider<select id="modelProvider" ${stopped ? 'disabled' : ''}>${providers}</select></label><label>Provider key<input id="modelApiKey" type="password" autocomplete="off" placeholder="Paste the key from your provider" ${stopped ? 'disabled' : ''}/></label><label>Create an unlock phrase<input id="modelPassphrase" type="password" autocomplete="new-password" minlength="10" placeholder="At least 10 characters; you will need it again" ${stopped ? 'disabled' : ''}/></label><p class="model-key-hint">The phrase encrypts the saved key on this browser. Keep it somewhere safe; HexiSpace cannot recover it.</p><details id="modelAdvancedOptions" class="setup-card model-advanced"><summary>Advanced model options</summary><label>Model name (optional)<input id="modelId" autocomplete="off" placeholder="Leave blank to use the first model offered" ${stopped ? 'disabled' : ''}/></label><label>Custom provider address<input id="modelEndpoint" type="url" autocomplete="url" value="${defaultEndpoint}" placeholder="https://api.example.com/v1" ${stopped ? 'disabled' : ''}/></label><p class="model-key-hint">Most providers need no address change. Choose “Another compatible provider” above to enter its address.</p></details><button class="primary-button" type="submit" ${stopped ? 'disabled' : ''}>Connect and test</button></form><p id="modelConnectionStatus" class="muted" role="status"></p>${savedConnections}<details class="setup-card"><summary>Change the app theme</summary><label>Theme<select id="appTheme">${themeOptions(selectedTheme)}</select></label></details></section>`;
}
