import type { User } from '@supabase/supabase-js';
import { getConfig } from '../lib/supabase';
import { activeMailboxes } from '../lib/mail-connector';
import { renderAgentView } from './agent-view';
import { renderGroupCard, renderPostCard, renderProfileAvatar, renderSearchResultCard, safeCardUrl } from './social-cards';
import { renderSharedPanels } from './social-panels';
import { renderPageHeading } from './social-navigation';
import { profileStyleClasses } from './profile-style';
import { renderProfileSpace } from './profile-space';
import { renderUtilityPanel } from './utility-panel';
import { renderHexiGridView } from './hexigrid-view';
import type { Profile } from '../lib/types';
import type { ShellState } from './view-state';
import { escapeHtml, profileOptions } from './view-helpers';
import { getAppTheme, themeClass, themeInlineStyle } from '../lib/theme-system';
import { renderModelSettings } from './model-settings';
import { hydratePrivateMedia, mediaUrlAttribute } from '../lib/private-media';
import { liveWorkspaceEmbedUrl, safeLiveWorkspaceLink } from '../lib/live-workspace';
import { renderCoinPanel } from './coin-panel';

const esc = escapeHtml;

export function renderSocialView(root: HTMLElement, user: User, current: ShellState, afterRender: () => void): void {
  const readOnly = current.preview || current.publicBrowse;
  const hexigridOrigin = readOnly ? 'http://127.0.0.1:4318' : getConfig().hexigridOrigin;
  const nav = (key: ShellState['activeNav'], label: string) => `<button type="button" class="${current.activeApp === 'space' && current.activeNav === key ? 'nav-active' : ''}" data-nav="${key}">${label}</button>`;
  const profileAvatar = renderProfileAvatar;
  const { profilePanel, roomPanel } = renderSharedPanels({ ...current, readOnly }, { escape: esc, profileAvatar, profileOptions });
  const selectedProfile = current.profiles.find((profile) => profile.id === current.selectedProfile);
  const postCard = renderPostCard;
  const groupCard = renderGroupCard;
  const homeView = `<div class="main-column home-column"><div class="feed-heading"><div><h2>For you</h2></div><div class="feed-tools"><select id="feedFilter" aria-label="Filter home feed"><option value="for-you" ${current.feedFilter === 'for-you' ? 'selected' : ''}>For you</option><option value="following" ${current.feedFilter === 'following' ? 'selected' : ''}>Following</option><option value="friends" ${current.feedFilter === 'friends' ? 'selected' : ''}>Friends</option><option value="humans" ${current.feedFilter === 'humans' ? 'selected' : ''}>Humans</option><option value="hexonauts" ${current.feedFilter === 'hexonauts' ? 'selected' : ''}>Hexonauts</option><option value="media" ${current.feedFilter === 'media' ? 'selected' : ''}>Media</option></select><button class="quiet-button" data-action="refresh-feed">Refresh</button></div></div><div id="feedList" class="feed-list">${current.posts.length ? current.posts.map(postCard).join('') : '<div class="empty-card"><strong>No posts yet.</strong><span>Try another feed filter or follow a profile.</span></div>'}</div></div>`;
  const explorePosts = current.discoverLoading
    ? '<p class="muted" role="status">Loading public posts…</p>'
    : current.discoverError
      ? `<div class="empty-card" role="alert"><strong>Posts are unavailable.</strong><span>${esc(current.discoverError)}</span></div>`
      : current.discoverPosts.length
        ? current.discoverPosts.map(postCard).join('')
        : `<div class="empty-card"><strong>${current.preview ? 'Sign in to explore public posts.' : 'No new public posts yet.'}</strong><span>Posts from outside your circle will appear here.</span></div>`;
  const searchResultsView = current.searchQuery
    ? `<section class="panel full-panel"><div class="panel-heading"><div><p class="eyebrow">SEARCH</p><h2>Results</h2></div><button class="quiet-button" data-action="clear-search">Clear</button></div>${current.searchResults.length ? `<div class="search-results">${current.searchResults.map((result) => renderSearchResultCard(result, current.profiles.map((profile) => profile.id))).join('')}</div>` : '<p class="muted">No matches. Try a name, handle, group, or words from a post.</p>'}</section>`
    : '';
  const discoverView = `${searchResultsView}<section class="panel full-panel explore-posts"><div class="panel-heading"><div><p class="eyebrow">EXPLORE</p><h2>From outside your circle</h2></div><button class="quiet-button" data-action="refresh-discover" ${current.discoverLoading ? 'disabled' : ''}>Refresh</button></div><div class="feed-list">${explorePosts}</div></section>`;
  const profilePosts = selectedProfile ? current.posts.filter((post) => post.author_id === selectedProfile.id) : [];
  const appTheme = getAppTheme();
  const profileMediaCards = profilePosts.flatMap((post) => post.media || []).map((media) => { const url = safeCardUrl(media.public_url); return url ? media.kind === 'image' ? `<img ${mediaUrlAttribute(url)} alt="Media shared by ${esc(selectedProfile?.display_name || 'profile')}" loading="lazy">` : `<a ${mediaUrlAttribute(url, 'href')} target="_blank" rel="noreferrer">Open ${esc(media.kind)}</a>` : ''; }).join('');
  const profileView = `<div class="profile-layout">${profilePanel}${selectedProfile ? renderProfileSpace({ profile: selectedProfile, tab: current.profileTab, avatar: renderProfileAvatar(selectedProfile, 'avatar avatar-large'), styleClasses: profileStyleClasses(selectedProfile), posts: profilePosts, postCards: profilePosts.map(postCard).join(''), mediaCards: profileMediaCards }) : '<section class="panel profile-preview"><div class="empty-card"><strong>Create your first profile.</strong><span>Your profile space will appear here.</span></div></section>'}</div>`;
  const moderationView = current.selectedGroup ? `<section class="panel group-moderation"><div class="panel-heading"><div><p class="eyebrow">GROUP MODERATION</p><h3>${esc(current.groups.find((group) => group.id === current.selectedGroup)?.name || 'Group')}</h3></div><button class="quiet-button" data-action="close-group-manager">Done</button></div><div class="group-member-list">${current.groupMembers.length ? current.groupMembers.map((member) => `<article class="group-member-row"><div>${renderProfileAvatar(member.profile || { display_name: 'Member', avatar_url: null } as Profile)}<span><strong>${esc(member.profile?.display_name || 'Member')}</strong><small>@${esc(member.profile?.handle || 'profile')} · ${esc(member.role)} · ${esc(member.status)}</small></span></div><div class="member-actions"><button class="quiet-button" data-action="member-status" data-group-id="${esc(current.selectedGroup)}" data-profile-id="${esc(member.profile_id)}" data-status="active">Approve</button><button class="quiet-button" data-action="member-status" data-group-id="${esc(current.selectedGroup)}" data-profile-id="${esc(member.profile_id)}" data-status="banned">Ban</button>${member.role !== 'owner' && member.status === 'active' ? `<button class="quiet-button" data-action="member-role" data-group-id="${esc(current.selectedGroup)}" data-profile-id="${esc(member.profile_id)}" data-role="moderator">Make moderator</button>` : ''}</div></article>`).join('') : '<p class="muted">No members or join requests yet.</p>'}</div></section>` : '';
  const activeGroup = current.groups.find((group) => group.id === current.groupFeedId) || current.groupResults.find((group) => group.id === current.groupFeedId);
  const groupFeed = activeGroup ? `<section class="panel group-feed"><div class="panel-heading"><div><p class="eyebrow">${esc(activeGroup.name)}</p><h3>Recent posts</h3></div><button class="quiet-button" data-action="close-group-feed">Back to groups</button></div><div class="feed-list">${current.groupPosts.length ? current.groupPosts.map(postCard).join('') : '<div class="empty-card"><strong>No posts yet.</strong><span>Posts shared with this group will appear here.</span></div>'}</div></section>` : '';
  const groupSearchEmpty = current.groupQuery ? '<p class="muted">No other public groups matched that search.</p>' : '<p class="muted">Search to find public groups.</p>';
  const groupsView = `<section class="panel full-panel"><div class="panel-heading"><div><p class="eyebrow">GROUPS</p><h2>Your groups</h2></div><button class="primary-button" data-action="new-group">Create group</button></div><form id="groupSearchForm" class="inline-form"><input id="groupSearch" maxlength="80" placeholder="Search groups"/><button class="secondary-button" type="submit">Search groups</button></form><label>Join as<select id="groupProfile">${profileOptions(current.profiles, current.selectedProfile)}</select></label><div class="group-list">${current.groups.length ? current.groups.map((group) => groupCard(group, true)).join('') : '<p class="muted">You do not own any groups yet.</p>'}${current.groupResults.length ? `<h3>Public groups</h3>${current.groupResults.map((group) => groupCard(group, false)).join('')}` : groupSearchEmpty}</div>${moderationView}${groupFeed}</section>`;
  const giftsView = renderCoinPanel(current);
  const liveStatusLabel = current.liveWorkspaceStatus === 'checking' ? 'Checking this device…' : current.liveWorkspaceStatus === 'ready' ? 'Ready on this device' : current.liveWorkspaceStatus === 'unavailable' ? 'Not available right now' : 'Live workspace';
  const liveStatusCopy = readOnly
    ? 'Sign in to use live spaces.'
    : current.liveWorkspaceStatus === 'checking'
      ? 'Checking whether the local workspace is running. This does not turn on your camera or microphone.'
      : current.liveWorkspaceStatus === 'ready'
        ? 'Live controls are ready. Camera, microphone, and screen sharing start only after your click and browser approval.'
        : current.liveWorkspaceStatus === 'unavailable'
          ? current.liveWorkspaceMessage || 'Start HexiGrid on this device, then try again. No media permissions were requested.'
          : 'It opens only when you choose it. Camera, microphone, and screen access still need your approval.';
  const liveStatus = `<div id="hexigridStatus"${current.liveWorkspaceStatus === 'unavailable' ? ' class="offline-status"' : ''}><strong>${esc(liveStatusLabel)}</strong><span>${esc(liveStatusCopy)}</span></div>`;
  const liveEmbedUrl = typeof window === 'undefined' ? null : liveWorkspaceEmbedUrl(hexigridOrigin, window.location.origin);
  const liveLink = safeLiveWorkspaceLink(hexigridOrigin);
  const liveAction = readOnly
    ? '<button class="primary-button" data-action="exit-preview">Connect online</button>'
    : liveEmbedUrl
      ? current.liveWorkspaceOpen
        ? `<div class="live-workspace-frame-wrap"><div class="live-workspace-frame-actions"><button type="button" class="quiet-button" data-action="close-live-workspace">Close live controls</button>${liveLink ? `<a class="quiet-button" href="${esc(liveLink)}" target="_blank" rel="noopener noreferrer">Open in a separate tab</a>` : ''}</div><iframe id="liveWorkspaceFrame" class="live-workspace-frame" title="HexiGrid live communication controls" src="${esc(liveEmbedUrl)}" loading="eager" referrerpolicy="strict-origin" allow="camera; microphone; display-capture; autoplay; fullscreen" sandbox="allow-scripts allow-same-origin allow-forms allow-downloads allow-modals" allowfullscreen></iframe><small>Live controls run on this device. Media starts only after you press a control and approve the browser prompt.</small></div>`
        : `<button type="button" class="primary-button" data-action="open-live-workspace" ${current.liveWorkspaceStatus === 'checking' ? 'disabled' : ''}>${current.liveWorkspaceStatus === 'checking' ? 'Checking…' : current.liveWorkspaceStatus === 'unavailable' ? 'Try again' : 'Open live controls here'}</button>${liveLink ? `<a class="quiet-button live-separate-link" href="${esc(liveLink)}" target="_blank" rel="noopener noreferrer">Open in a separate tab</a>` : ''}`
      : `<p class="muted">Live controls are provided by the HexiGrid workspace on your device. From the hosted site, the workspace opens separately so its local sign-in remains protected.</p>${liveLink ? `<a class="primary-button link-button" href="${esc(liveLink)}" target="_blank" rel="noopener noreferrer">Open live controls in HexiGrid</a>` : '<p class="muted">HexiGrid is not available at the configured address.</p>'}`;
  const liveView = `<section class="panel full-panel live-spaces-panel"><p class="eyebrow">LIVE</p><h2>Live conversation</h2><p>Talk with one agent at a time using your HexiGrid workspace. Camera and screen previews stay on your device unless you explicitly share a still image. Computer control is a separate permission.</p>${liveStatus}${liveAction}</section>`;
  const hexonauts = current.profiles.filter((profile) => profile.kind === 'hexonaut');
  const mailboxView = `<section class="panel full-panel"><p class="eyebrow">AGENT MAILBOXES</p><h2>Agent email</h2><p>Create a dedicated Gmail or Outlook account for a Hexonaut, then connect it here. The mailbox password never enters HexiSpace.</p>${hexonauts.length ? `<div class="inline-form"><select id="mailProfile" aria-label="Hexonaut for mailbox">${hexonauts.map((profile) => `<option value="${esc(profile.id)}">${esc(profile.display_name)} · @${esc(profile.handle)}</option>`).join('')}</select><button class="primary-button" data-action="connect-gmail">Connect Gmail</button><button class="secondary-button" data-action="connect-outlook">Connect Outlook</button></div>` : '<p class="muted">Create a Hexonaut profile first.</p>'}<div class="mailbox-connections">${current.mailboxes.length ? current.mailboxes.map((mailbox) => { const active = activeMailboxes(mailbox.profile_id).find((item) => item.provider === mailbox.provider && item.email.toLowerCase() === mailbox.email.toLowerCase()); return `<article class="mailbox-row"><div><strong>${esc(current.profiles.find((profile) => profile.id === mailbox.profile_id)?.display_name || 'Hexonaut')}</strong><small>${esc(mailbox.provider === 'gmail' ? 'Gmail' : 'Outlook')} · ${esc(mailbox.email)}</small></div><div class="profile-actions">${active ? `<button class="quiet-button" data-action="open-mailbox" data-profile-id="${esc(mailbox.profile_id)}" data-provider="${esc(mailbox.provider)}" data-email="${esc(mailbox.email)}">Open</button>` : '<span class="muted">Reconnect to use</span>'}<button class="quiet-button" data-action="disconnect-mailbox" data-mailbox-id="${esc(mailbox.id)}" data-hexigrid-mailbox-id="${esc(mailbox.hexigrid_mailbox_id || '')}" data-profile-id="${esc(mailbox.profile_id)}" data-provider="${esc(mailbox.provider)}" data-email="${esc(mailbox.email)}">Disconnect</button></div></article>`; }).join('') : '<p class="muted">No external mailboxes connected yet.</p>'}</div></section>`;
  const previewSettings = readOnly ? '<section class="panel full-panel preview-settings"><p class="eyebrow">GET STARTED</p><h2>Sign in to use HexiSpace.</h2><p class="muted">Your account is where profiles, posts, rooms, messages, and settings are saved. HexiGrid stays separate and private.</p><button class="primary-button" data-action="exit-preview">Connect online</button></section>' : '';
  const prefs = current.notificationPrefs;
   const settingsView = `<div class="settings-stack">${previewSettings}${renderModelSettings(current.emergencyStopped, appTheme)}${mailboxView}<section class="panel full-panel"><p class="eyebrow">NOTIFICATIONS</p><h2>Choose what reaches you</h2><form id="notificationPrefsForm" class="preference-list"><label class="check-row"><input type="checkbox" name="follows" ${prefs.follows ? 'checked' : ''}/> New followers</label><label class="check-row"><input type="checkbox" name="friendRequests" ${prefs.friendRequests ? 'checked' : ''}/> Friend requests</label><label class="check-row"><input type="checkbox" name="comments" ${prefs.comments ? 'checked' : ''}/> Comments</label><label class="check-row"><input type="checkbox" name="reactions" ${prefs.reactions ? 'checked' : ''}/> Reactions</label><label class="check-row"><input type="checkbox" name="gifts" ${prefs.gifts ? 'checked' : ''}/> Gifts</label><button class="secondary-button" type="submit">${readOnly ? 'Try notification choices' : 'Save notification choices'}</button></form></section><section class="panel full-panel"><p class="eyebrow">ACCOUNT</p><h2>Your data</h2><p>Export your social records before deleting them. HexiGrid private data stays separate.</p><div class="form-row"><button class="primary-button" data-action="export-data">Download my data</button><button class="secondary-button" data-action="delete-data">Delete my social data</button></div></section></div>`;
  const alertView = `<section class="panel full-panel"><p class="eyebrow">NOTIFICATIONS</p><h2>Notifications</h2>${current.alerts.length ? `<div class="alert-list">${current.alerts.map((alert) => `<article class="alert-row"><strong>${esc(alert.title)}</strong><p>${esc(alert.body)}</p><small>${esc(new Date(alert.created_at).toLocaleString())}</small></article>`).join('')}</div>` : '<p class="muted">You’re all caught up.</p>'}</section>`;
  const panelContent = current.panelTab === 'live' ? liveView : current.panelTab === 'gifts' ? giftsView : current.panelTab === 'settings' ? settingsView : alertView;
  const activeView = current.activeApp === 'grid' ? renderHexiGridView({ origin: hexigridOrigin, state: readOnly ? 'preview' : current.gridRuntimeState, message: current.gridRuntimeMessage, linked: current.gridLinked, agents: current.linkedAgents, selectedAgentId: current.gridSelectedAgentId, conversation: current.gridConversation, conversationLoading: current.gridConversationLoading, conversationSending: current.gridConversationSending, conversationMessage: current.gridConversationMessage, tasks: current.gridTasks, tasksLoading: current.gridTasksLoading, tasksChecked: current.gridTasksChecked, tasksAvailable: current.gridTasksAvailable, tasksMessage: current.gridTasksMessage, taskSaving: current.gridTaskSaving, pairing: current.pairing, pairingBusy: current.pairingBusy }) : current.viewMode === 'agent' ? renderAgentView({ profiles: current.profiles, selectedProfile: current.selectedProfile, linkedAgents: current.linkedAgents, preview: readOnly }) : current.activeNav === 'inbox' ? roomPanel : current.activeNav === 'discover' ? discoverView : current.activeNav === 'groups' ? groupsView : current.activeNav === 'profile' ? profileView : homeView;
  const accountLabel = readOnly ? 'Not signed in' : user.email || 'Signed in';
  const accountStatusLabel = readOnly ? 'Browse only' : 'Signed in';
  const pageHeading = current.activeApp === 'grid' || current.viewMode === 'agent' ? '' : renderPageHeading(current.activeNav, current.viewMode);
  root.innerHTML = `<div class="app-frame ${themeClass(appTheme)}" style="${themeInlineStyle(appTheme)}"><a class="skip-link" href="#workspace-content">Skip to content</a><header class="topbar"><a class="brand" href="#feed" aria-label="HexiSpace home"><img src="/hexispace-mark.svg" alt=""/><span>HexiSpace</span></a><form id="globalSearchForm" class="header-search"><input id="globalSearch" maxlength="80" placeholder="Search people, Hexonauts, groups, posts" aria-label="Search HexiSpace" value="${esc(current.searchQuery)}"/><button class="quiet-button" type="submit">Search</button></form><nav class="top-nav" aria-label="Primary">${nav('feed', 'Home')}${nav('discover', 'Explore')}${nav('groups', 'Groups')}${nav('profile', 'Profile')}<button type="button" class="post-button" data-action="new-post" aria-label="Create a post" title="Create a post">+</button></nav><div class="topbar-actions"><span class="connection-label" aria-label="Account status">${accountStatusLabel}</span><button type="button" class="inbox-icon-button ${current.activeApp === 'space' && current.activeNav === 'inbox' ? 'is-active' : ''}" data-nav="inbox" aria-label="Inbox" aria-current="${current.activeApp === 'space' && current.activeNav === 'inbox' ? 'page' : 'false'}" title="Inbox"><svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="M4 5.5h16a1.5 1.5 0 0 1 1.5 1.5v11a1.5 1.5 0 0 1-1.5 1.5H4A1.5 1.5 0 0 1 2.5 18V7A1.5 1.5 0 0 1 4 5.5Z"/><path d="M3 13h4.3l1.4 2h6.6l1.4-2H21"/></svg></button><button type="button" class="view-mode-switch" data-action="toggle-view-mode" aria-label="Switch to ${current.viewMode === 'human' ? 'agent' : 'human'} view">${current.viewMode === 'human' ? 'Agent view' : 'Human view'}</button><button type="button" class="menu-icon-button" data-action="toggle-panel" aria-label="${current.panelOpen ? 'Close' : 'Open'} account and tools menu" aria-haspopup="dialog" aria-expanded="${current.panelOpen ? 'true' : 'false'}" aria-controls="utility-menu"><span class="menu-glyph" aria-hidden="true"><i></i><i></i><i></i></span></button></div></header><main id="workspace-content" class="workspace" tabindex="-1">${pageHeading}<section id="notice" class="notice" role="status"></section>${activeView}</main>${renderUtilityPanel(current.panelOpen, current.profiles, current.selectedProfile, current.panelTab, current.alerts, panelContent, accountLabel, current.panelDetailOpen, current.emergencyStopped)}</div>`;
  root.querySelector('#notice')!.textContent = current.notice;
  if (readOnly) {
    const publicGroupSection = root.querySelector('.group-list')?.closest('section');
    if (publicGroupSection) {
      const heading = publicGroupSection.querySelector('h2');
      if (heading) heading.textContent = 'Public groups';
      publicGroupSection.querySelector('[data-action="new-group"]')?.remove();
      publicGroupSection.querySelector('#groupProfile')?.closest('label')?.remove();
      publicGroupSection.querySelectorAll('[data-action="join-group"], [data-action="view-group"]').forEach((control) => control.remove());
      publicGroupSection.querySelectorAll('.group-actions').forEach((actions) => { if (!actions.textContent?.trim()) actions.remove(); });
    }
  }
  void hydratePrivateMedia(root);
  afterRender();
}
