import type { HexiGridConversationMessage, HexiGridTask, LinkedAgent, PairingRequest } from '../lib/hexigrid-bridge';
import type { NotificationPreferences } from '../lib/social-preferences';
import type { CoinLedgerEntry, FeedFilter, GiftCatalogItem, Group, GroupMember, MailboxConnection, Message, Notification, Post, Profile, Room, RoomSummary, SearchResult } from '../lib/types';
import type { ReceivedGift } from '../lib/gift-store';
import type { ProfileTab } from './profile-space';
import type { UtilityTab } from './utility-panel';
import type { ReferralStatus } from '../lib/referral-store';

export type ShellState = {
  profiles: Profile[];
  posts: Post[];
  rooms: RoomSummary[];
  groups: Group[];
  groupResults: Group[];
  groupQuery: string;
  groupMembers: GroupMember[];
  selectedGroup: string;
  groupFeedId: string;
  groupPosts: Post[];
  giftItems: GiftCatalogItem[];
  receivedGifts: ReceivedGift[];
  giftBalance: number;
  coinHistory: CoinLedgerEntry[];
  coinStatus: 'idle' | 'loading' | 'ready' | 'unavailable';
  referral: ReferralStatus | null;
  searchResults: SearchResult[];
  searchQuery: string;
  mailboxes: MailboxConnection[];
  alerts: Notification[];
  notificationPrefs: NotificationPreferences;
  mutedProfileIds: string[];
  discoverPosts: Post[];
  discoverLoading: boolean;
  discoverError: string;
  selectedProfile: string;
  selectedRoom: string;
  roomMessages: Message[];
  linkedAgents: LinkedAgent[];
  gridSelectedAgentId: string;
  gridConversation: HexiGridConversationMessage[];
  gridConversationLoading: boolean;
  gridConversationSending: boolean;
  gridConversationMessage: string;
  gridTasks: HexiGridTask[];
  gridTasksLoading: boolean;
  gridTasksChecked: boolean;
  gridTasksAvailable: boolean;
  gridTasksMessage: string;
  gridTaskSaving: boolean;
  liveWorkspaceOpen: boolean;
  liveWorkspaceStatus: 'idle' | 'checking' | 'ready' | 'unavailable';
  liveWorkspaceMessage: string;
  activeNav: 'feed' | 'discover' | 'groups' | 'inbox' | 'profile';
  activeApp: 'space' | 'grid';
  gridRuntimeState: 'preview' | 'checking' | 'online' | 'offline';
  gridRuntimeMessage: string;
  gridLinked: boolean;
  profileTab: ProfileTab;
  viewMode: 'human' | 'agent';
  panelOpen: boolean;
  panelDetailOpen: boolean;
  panelTab: UtilityTab;
  feedFilter: FeedFilter;
  notice: string;
  busy: boolean;
  stopRoom: (() => void) | null;
  pairing: PairingRequest | null;
  pairingBusy: boolean;
  preview: boolean;
  publicBrowse: boolean;
  emergencyStopped: boolean;
};
