-- Add a privacy-preserving network velocity guard before Supabase creates an
-- account. No raw IP address, email address, or user ID is retained here.

create table if not exists private.hexicoin_signup_guard_key (
  singleton boolean primary key default true check (singleton),
  key_material bytea not null check (octet_length(key_material) >= 32),
  created_at timestamptz not null default now()
);
revoke all on table private.hexicoin_signup_guard_key from public, anon, authenticated, service_role, supabase_auth_admin;

-- UUIDs are generated by PostgreSQL's cryptographically secure UUID generator.
-- Their concatenated bytes become a private HMAC key and are never returned.
insert into private.hexicoin_signup_guard_key(singleton, key_material)
values (true, pg_catalog.convert_to(pg_catalog.gen_random_uuid()::text || pg_catalog.gen_random_uuid()::text, 'UTF8'))
on conflict (singleton) do nothing;

create table if not exists private.hexicoin_signup_guard_events (
  event_id uuid primary key,
  ip_digest text not null check (ip_digest ~ '^[a-f0-9]{64}$'),
  accepted boolean not null,
  risk_flags text[] not null default '{}',
  created_at timestamptz not null default clock_timestamp(),
  check (coalesce(array_length(risk_flags, 1), 0) <= 4)
);
create index if not exists hexicoin_signup_guard_ip_time_idx
  on private.hexicoin_signup_guard_events(ip_digest, created_at desc);
revoke all on table private.hexicoin_signup_guard_events from public, anon, authenticated, service_role, supabase_auth_admin;

create or replace function private.hexicoin_signup_ip_digest(p_ip inet)
returns text
language plpgsql
security definer
set search_path = ''
as $function$
declare
  crypto_schema name;
  secret_key bytea;
  result text;
begin
  if p_ip is null then raise exception 'Signup network signal is missing.'; end if;
  select key_material into secret_key
  from private.hexicoin_signup_guard_key where singleton;
  select namespace.nspname into crypto_schema
  from pg_catalog.pg_extension installed
  join pg_catalog.pg_namespace namespace on namespace.oid = installed.extnamespace
  where installed.extname = 'pgcrypto';
  if secret_key is null or crypto_schema is null then
    raise exception 'Signup protection is not configured.';
  end if;

  -- pgcrypto can already live in public or another schema on an existing
  -- project. Resolve its installed schema instead of moving the extension.
  execute pg_catalog.format(
    'select pg_catalog.encode(%I.hmac(pg_catalog.convert_to($1, ''UTF8''), $2, ''sha256''), ''hex'')',
    crypto_schema
  ) into result using pg_catalog.host(p_ip), secret_key;
  return result;
end;
$function$;

create or replace function public.hexispace_before_user_created(event jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  event_uuid uuid;
  event_user_id uuid;
  source_ip inet;
  network_digest text;
  prior_decision boolean;
  accounts_last_hour integer;
  accounts_last_day integer;
  accepted_signup boolean;
  signals text[] := array[]::text[];
begin
  if pg_catalog.jsonb_typeof(event) <> 'object'
    or coalesce(event #>> '{metadata,name}', '') <> 'before-user-created' then
    return pg_catalog.jsonb_build_object('error', pg_catalog.jsonb_build_object(
      'http_code', 400, 'message', 'The signup request could not be verified. Please try again.'
    ));
  end if;

  begin
    event_uuid := nullif(pg_catalog.btrim(event #>> '{metadata,uuid}'), '')::uuid;
    source_ip := nullif(pg_catalog.btrim(event #>> '{metadata,ip_address}'), '')::inet;
    event_user_id := nullif(pg_catalog.btrim(event #>> '{user,id}'), '')::uuid;
  exception when others then
    return pg_catalog.jsonb_build_object('error', pg_catalog.jsonb_build_object(
      'http_code', 503, 'message', 'Signup protection is temporarily unavailable. Please try again in a few minutes.'
    ));
  end;

  if event_uuid is null or source_ip is null or event_user_id is null then
    return pg_catalog.jsonb_build_object('error', pg_catalog.jsonb_build_object(
      'http_code', 503, 'message', 'Signup protection is temporarily unavailable. Please try again in a few minutes.'
    ));
  end if;

  select accepted into prior_decision
  from private.hexicoin_signup_guard_events where event_id = event_uuid;
  if found then
    if prior_decision then return '{}'::jsonb; end if;
    return pg_catalog.jsonb_build_object('error', pg_catalog.jsonb_build_object(
      'http_code', 429, 'message', 'Too many new accounts were created from this network. Please try again later.'
    ));
  end if;

  begin
    network_digest := private.hexicoin_signup_ip_digest(source_ip);
  exception when others then
    return pg_catalog.jsonb_build_object('error', pg_catalog.jsonb_build_object(
      'http_code', 503, 'message', 'Signup protection is temporarily unavailable. Please try again in a few minutes.'
    ));
  end;

  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(network_digest, 0));
  select count(*)::integer into accounts_last_hour
  from private.hexicoin_signup_guard_events
  where ip_digest = network_digest and accepted
    and created_at >= pg_catalog.clock_timestamp() - interval '1 hour';
  select count(*)::integer into accounts_last_day
  from private.hexicoin_signup_guard_events
  where ip_digest = network_digest and accepted
    and created_at >= pg_catalog.clock_timestamp() - interval '24 hours';

  accepted_signup := accounts_last_hour < 8 and accounts_last_day < 20;
  if accounts_last_hour >= 8 then signals := pg_catalog.array_append(signals, 'hourly_signup_limit'); end if;
  if accounts_last_day >= 20 then signals := pg_catalog.array_append(signals, 'daily_signup_limit'); end if;
  if accepted_signup and accounts_last_hour >= 4 then
    signals := pg_catalog.array_append(signals, 'elevated_hourly_signup_velocity');
  end if;
  if accepted_signup and accounts_last_day >= 10 then
    signals := pg_catalog.array_append(signals, 'elevated_daily_signup_velocity');
  end if;

  insert into private.hexicoin_signup_guard_events(event_id, ip_digest, accepted, risk_flags)
  values (event_uuid, network_digest, accepted_signup, signals)
  on conflict (event_id) do nothing;

  -- A duplicate event arriving concurrently is replayed consistently rather
  -- than counted twice or allowed to change its earlier decision.
  if not found then
    select accepted into prior_decision
    from private.hexicoin_signup_guard_events where event_id = event_uuid;
    if prior_decision then return '{}'::jsonb; end if;
    return pg_catalog.jsonb_build_object('error', pg_catalog.jsonb_build_object(
      'http_code', 429, 'message', 'Too many new accounts were created from this network. Please try again later.'
    ));
  end if;

  if accepted_signup then return '{}'::jsonb; end if;
  return pg_catalog.jsonb_build_object('error', pg_catalog.jsonb_build_object(
    'http_code', 429, 'message', 'Too many new accounts were created from this network. Please try again later.'
  ));
exception when others then
  -- Do not leak database details, auth payloads, or the IP to the caller.
  return pg_catalog.jsonb_build_object('error', pg_catalog.jsonb_build_object(
    'http_code', 503, 'message', 'Signup protection is temporarily unavailable. Please try again in a few minutes.'
  ));
end;
$function$;

create or replace function private.cleanup_hexicoin_signup_guard_events()
returns integer
language plpgsql
security definer
set search_path = ''
as $function$
declare
  removed integer;
begin
  delete from private.hexicoin_signup_guard_events
  where created_at < pg_catalog.clock_timestamp() - interval '30 days';
  get diagnostics removed = row_count;
  return removed;
end;
$function$;

create or replace function public.admin_list_hexicoin_signup_abuse()
returns table (
  first_seen timestamptz,
  last_seen timestamptz,
  account_creations integer,
  blocked_attempts integer,
  signals text[]
)
language plpgsql
security definer
set search_path = ''
as $function$
begin
  if not exists (
    select 1 from public.platform_admins where user_id = (select auth.uid())
  ) then raise exception 'Not authorized to review signup activity.'; end if;

  return query
  with flagged_network_days as (
    select distinct events.ip_digest, pg_catalog.date_trunc('day', events.created_at) as review_day
    from private.hexicoin_signup_guard_events events
    where events.created_at >= pg_catalog.clock_timestamp() - interval '30 days'
      and pg_catalog.cardinality(events.risk_flags) > 0
  )
  select min(events.created_at), max(events.created_at),
         count(distinct events.event_id) filter (where events.accepted)::integer,
         count(distinct events.event_id) filter (where not events.accepted)::integer,
         array_agg(distinct signal.flag order by signal.flag)
  from flagged_network_days flagged
  join private.hexicoin_signup_guard_events events
    on events.ip_digest = flagged.ip_digest
   and pg_catalog.date_trunc('day', events.created_at) = flagged.review_day
  left join lateral pg_catalog.unnest(events.risk_flags) as signal(flag) on true
  group by flagged.ip_digest, flagged.review_day
  order by min(events.created_at) desc
  limit 100;
end;
$function$;

revoke all on function private.hexicoin_signup_ip_digest(inet) from public, anon, authenticated, service_role, supabase_auth_admin;
revoke all on function private.cleanup_hexicoin_signup_guard_events() from public, anon, authenticated, service_role, supabase_auth_admin;
revoke all on function public.hexispace_before_user_created(jsonb) from public, anon, authenticated, service_role;
grant usage on schema public to supabase_auth_admin;
grant execute on function public.hexispace_before_user_created(jsonb) to supabase_auth_admin;
revoke all on function public.admin_list_hexicoin_signup_abuse() from public, anon;
grant execute on function public.admin_list_hexicoin_signup_abuse() to authenticated;

select cron.schedule(
  'hexicoin-signup-guard-cleanup',
  '29 4 * * *',
  'select private.cleanup_hexicoin_signup_guard_events()'
);
